import { mkdir, readFile, writeFile } from "node:fs/promises";
import { basename, dirname, extname, join, relative } from "node:path";
import fg from "fast-glob";
import {
  AUTO_IGNORE_GLOBS,
  DEFAULT_COMPONENT_GLOBS_BY_FRAMEWORK,
  DEFAULT_IGNORE_GLOBS,
} from "../constants.js";
import { OpenstoryCliNoComponentsFoundError } from "../errors.js";
import { detectFramework } from "../plugin/framework-detection.js";
import type { Framework } from "../types.js";
import { type DetectedComponent, findComponentsInFile } from "../utils/find-components.js";

export interface AutoOptions {
  globs: string[];
  framework?: Framework;
  outDir?: string;
  force: boolean;
  dryRun: boolean;
  json: boolean;
  ignore: string[];
}

export interface AutoGeneratedEntry {
  componentSourcePath: string;
  storyFilePath: string;
  components: DetectedComponent[];
  title: string;
  status: "written" | "skipped" | "planned";
}

export interface AutoResult {
  framework: Framework;
  generated: AutoGeneratedEntry[];
  searchedGlobs: string[];
}

const STORY_EXTENSION_BY_FRAMEWORK: Record<Framework, string> = {
  react: ".stories.tsx",
  solid: ".stories.tsx",
  vue: ".stories.ts",
  svelte: ".stories.ts",
};

const titleSegmentFromSegment = (segment: string): string => {
  const cleaned = segment.replace(/[^A-Za-z0-9]+/g, " ").trim();
  if (cleaned === "") return "";
  return cleaned
    .split(/\s+/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
};

const deriveTitleFromRelativePath = (relativePath: string): string => {
  const withoutExtension = relativePath.replace(/\.[^./]+$/, "");
  const normalized = withoutExtension.split("\\").join("/");
  const segments = normalized
    .split("/")
    .filter((segment) => segment.length > 0 && segment !== "src");
  if (segments.length === 0) return "Components";
  return segments
    .map((segment) => titleSegmentFromSegment(segment))
    .filter((segment) => segment.length > 0)
    .join("/");
};

const buildReactStoryFile = (
  framework: "react" | "solid",
  componentSourcePath: string,
  componentTargetPath: string,
  title: string,
  components: DetectedComponent[],
): string => {
  const defaultExport = components.find((entry) => entry.isDefaultExport);
  const namedExports = components.filter((entry) => !entry.isDefaultExport);
  const primary =
    defaultExport ??
    components[0] ??
    ({ name: "Component", isDefaultExport: false } satisfies DetectedComponent);

  const namedToImport = namedExports.filter((entry) => entry.name !== primary.name);
  const importParts: string[] = [];
  if (primary.isDefaultExport) {
    importParts.push(primary.name);
    if (namedToImport.length > 0) {
      importParts.push(`{ ${namedToImport.map((entry) => entry.name).join(", ")} }`);
    }
  } else {
    const namedSet = [primary, ...namedToImport].map((entry) => entry.name);
    importParts.push(`{ ${namedSet.join(", ")} }`);
  }
  const importClause = importParts.join(", ");
  const importSpecifier = relative(dirname(componentTargetPath), componentSourcePath)
    .split("\\")
    .join("/")
    .replace(/\.[^./]+$/, "");
  const importPath = importSpecifier.startsWith(".") ? importSpecifier : `./${importSpecifier}`;

  const storyExports = components.map((entry, index) => {
    const exportName = index === 0 ? "Default" : entry.name;
    return `export const ${exportName}: StoryObj<typeof meta> = {\n  args: {},\n  render: () => <${entry.name} />,\n};`;
  });

  return `import type { Meta, StoryObj } from "openstory/${framework}";
import ${importClause} from "${importPath}";

const meta: Meta = {
  title: "${title}",
  component: ${primary.name},
};
export default meta;

${storyExports.join("\n\n")}
`;
};

const buildSfcStoryFile = (
  framework: "vue" | "svelte",
  componentSourcePath: string,
  componentTargetPath: string,
  title: string,
  componentName: string,
): string => {
  const importSpecifier = relative(dirname(componentTargetPath), componentSourcePath)
    .split("\\")
    .join("/");
  const importPath = importSpecifier.startsWith(".") ? importSpecifier : `./${importSpecifier}`;

  return `import type { Meta, StoryObj } from "openstory/${framework}";
import ${componentName} from "${importPath}";

const meta: Meta = {
  title: "${title}",
  component: ${componentName},
};
export default meta;

export const Default: StoryObj<typeof meta> = {
  args: {},
};
`;
};

const buildStoryFileSource = (
  framework: Framework,
  componentSourcePath: string,
  componentTargetPath: string,
  title: string,
  components: DetectedComponent[],
): string => {
  if (framework === "vue" || framework === "svelte") {
    const componentName = components[0]?.name ?? "Component";
    return buildSfcStoryFile(
      framework,
      componentSourcePath,
      componentTargetPath,
      title,
      componentName,
    );
  }
  return buildReactStoryFile(
    framework,
    componentSourcePath,
    componentTargetPath,
    title,
    components,
  );
};

const storyTargetPath = (
  options: AutoOptions,
  projectRoot: string,
  componentSourcePath: string,
  framework: Framework,
): string => {
  const extension = STORY_EXTENSION_BY_FRAMEWORK[framework];
  const sourceBasename = basename(componentSourcePath, extname(componentSourcePath));
  const storyFileName = `${sourceBasename}${extension}`;
  if (options.outDir) {
    const outputDirectory = join(projectRoot, options.outDir);
    return join(outputDirectory, storyFileName);
  }
  return join(dirname(componentSourcePath), storyFileName);
};

const tryReadFile = async (absolutePath: string): Promise<string | undefined> => {
  try {
    return await readFile(absolutePath, "utf8");
  } catch {
    return undefined;
  }
};

export const runAuto = async (projectRoot: string, options: AutoOptions): Promise<AutoResult> => {
  const framework = options.framework ?? (await detectFramework(projectRoot));
  const defaultGlobs = DEFAULT_COMPONENT_GLOBS_BY_FRAMEWORK[framework] ?? [];
  const searchGlobs = options.globs.length > 0 ? options.globs : defaultGlobs;
  const ignoreGlobs = [...DEFAULT_IGNORE_GLOBS, ...AUTO_IGNORE_GLOBS, ...options.ignore];

  const candidateFiles = await fg(searchGlobs, {
    cwd: projectRoot,
    ignore: ignoreGlobs,
    absolute: true,
    onlyFiles: true,
    followSymbolicLinks: false,
  });

  const generated: AutoGeneratedEntry[] = [];
  for (const componentSourcePath of candidateFiles.sort()) {
    const source = (await tryReadFile(componentSourcePath)) ?? "";
    const components = findComponentsInFile(source, componentSourcePath, framework);
    if (components.length === 0) continue;

    const storyFilePath = storyTargetPath(options, projectRoot, componentSourcePath, framework);
    const relativeSource = relative(projectRoot, componentSourcePath).split("\\").join("/");
    const title = deriveTitleFromRelativePath(relativeSource);

    const existing = await tryReadFile(storyFilePath);
    if (existing !== undefined && !options.force) {
      generated.push({
        componentSourcePath,
        storyFilePath,
        components,
        title,
        status: "skipped",
      });
      continue;
    }

    const storySource = buildStoryFileSource(
      framework,
      componentSourcePath,
      storyFilePath,
      title,
      components,
    );

    if (!options.dryRun) {
      await mkdir(dirname(storyFilePath), { recursive: true });
      await writeFile(storyFilePath, storySource, "utf8");
    }
    generated.push({
      componentSourcePath,
      storyFilePath,
      components,
      title,
      status: options.dryRun ? "planned" : "written",
    });
  }

  const writtenCount = generated.filter((entry) => entry.status === "written").length;
  const plannedCount = generated.filter((entry) => entry.status === "planned").length;
  const skippedCount = generated.filter((entry) => entry.status === "skipped").length;

  if (generated.length === 0) {
    throw new OpenstoryCliNoComponentsFoundError(searchGlobs);
  }

  const result: AutoResult = {
    framework,
    generated,
    searchedGlobs: searchGlobs,
  };

  if (options.json) {
    process.stdout.write(`${JSON.stringify(result, null, 2)}\n`);
    return result;
  }

  const summaryLines: string[] = [
    `auto: framework=${framework} globs=${searchGlobs.join(",")}`,
    `      written=${writtenCount} planned=${plannedCount} skipped=${skippedCount}`,
    "",
  ];
  for (const entry of generated) {
    const relativeStoryPath = relative(projectRoot, entry.storyFilePath).split("\\").join("/");
    const relativeSourcePath = relative(projectRoot, entry.componentSourcePath)
      .split("\\")
      .join("/");
    const componentNames = entry.components.map((component) => component.name).join(", ");
    summaryLines.push(
      `  [${entry.status}] ${relativeStoryPath}  <- ${relativeSourcePath}  (${componentNames})`,
    );
  }
  summaryLines.push("");
  if (options.dryRun) {
    summaryLines.push("Dry run. No files written. Re-run without --dry-run to apply.");
  } else {
    summaryLines.push("Done. Run `openstory dev` to browse the generated stories.");
  }
  process.stdout.write(`${summaryLines.join("\n")}\n`);

  return result;
};
