import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { generateStoriesForProject } from "../../src/utils/generate-stories.js";
import { fileExists } from "../../src/utils/file-exists.js";

let projectRoot: string;

beforeEach(async () => {
  projectRoot = await mkdtemp(join(tmpdir(), "openstory-generate-"));
});

afterEach(async () => {
  await rm(projectRoot, { recursive: true, force: true });
});

const writeFixture = async (relativePath: string, contents: string): Promise<string> => {
  const absolutePath = join(projectRoot, relativePath);
  await mkdir(join(absolutePath, ".."), { recursive: true });
  await writeFile(absolutePath, contents, "utf8");
  return absolutePath;
};

describe("generateStoriesForProject", () => {
  it("writes a story file next to each detected component", async () => {
    await writeFixture(
      "src/components/Button.tsx",
      `interface Props { variant: "primary" | "ghost" }\nexport const Button = (props: Props) => null;\n`,
    );
    await writeFixture(
      "src/components/Card.tsx",
      `export const Card = (props: { title: string }) => null;\n`,
    );

    const report = await generateStoriesForProject({
      projectRoot,
      framework: "react",
      targets: ["src/components/*.tsx"],
    });

    expect(report.results.map((result) => result.status)).toEqual(["written", "written"]);
    expect(await fileExists(join(projectRoot, "src/components/Button.stories.tsx"))).toBe(true);
    expect(await fileExists(join(projectRoot, "src/components/Card.stories.tsx"))).toBe(true);
  });

  it("accepts a single absolute file path as a target", async () => {
    const absoluteComponentPath = await writeFixture(
      "src/widget.tsx",
      `export const Widget = (props: { label: string }) => null;\n`,
    );
    const report = await generateStoriesForProject({
      projectRoot,
      framework: "react",
      targets: [absoluteComponentPath],
    });
    expect(report.results).toHaveLength(1);
    expect(report.results[0]?.status).toBe("written");
  });

  it("skips a component when its story file already exists and force is false", async () => {
    await writeFixture(
      "src/Button.tsx",
      `export const Button = (props: { label: string }) => null;\n`,
    );
    await writeFixture("src/Button.stories.tsx", `// existing\n`);

    const report = await generateStoriesForProject({
      projectRoot,
      framework: "react",
      targets: ["src/*.tsx"],
    });
    expect(report.results[0]?.status).toBe("skipped-exists");
    const existingContents = await readFile(join(projectRoot, "src/Button.stories.tsx"), "utf8");
    expect(existingContents).toBe("// existing\n");
  });

  it("overwrites an existing story file when force is true", async () => {
    await writeFixture(
      "src/Button.tsx",
      `export const Button = (props: { label: string }) => null;\n`,
    );
    await writeFixture("src/Button.stories.tsx", `// existing\n`);

    const report = await generateStoriesForProject({
      projectRoot,
      framework: "react",
      targets: ["src/*.tsx"],
      force: true,
    });
    expect(report.results[0]?.status).toBe("written");
    const newContents = await readFile(join(projectRoot, "src/Button.stories.tsx"), "utf8");
    expect(newContents).toContain("// Generated by openstory.");
  });

  it("does not write files when dryRun is true", async () => {
    await writeFixture(
      "src/Button.tsx",
      `export const Button = (props: { label: string }) => null;\n`,
    );

    const report = await generateStoriesForProject({
      projectRoot,
      framework: "react",
      targets: ["src/*.tsx"],
      dryRun: true,
    });
    expect(report.results[0]?.status).toBe("written");
    expect(await fileExists(join(projectRoot, "src/Button.stories.tsx"))).toBe(false);
  });

  it("ignores .stories.tsx, .test.tsx, .spec.tsx, and preview files when globbing for components", async () => {
    await writeFixture("src/OldStory.stories.tsx", `export const Foo = () => null;`);
    await writeFixture("src/Bar.test.tsx", `export const Bar = () => null;`);
    await writeFixture("src/Baz.spec.tsx", `export const Baz = () => null;`);
    await writeFixture("src/preview.tsx", `export default {};`);
    await writeFixture(
      "src/Widget.tsx",
      `export const Widget = (props: { label: string }) => null;`,
    );
    const report = await generateStoriesForProject({
      projectRoot,
      framework: "react",
      targets: ["src/**/*.tsx"],
    });
    const writtenNames = report.results
      .filter((result) => result.status === "written")
      .map((result) => result.componentName);
    expect(writtenNames).toEqual(["Widget"]);
    expect(await fileExists(join(projectRoot, "src/OldStory.stories.stories.tsx"))).toBe(false);
    expect(await fileExists(join(projectRoot, "src/Bar.test.stories.tsx"))).toBe(false);
    expect(await fileExists(join(projectRoot, "src/preview.stories.tsx"))).toBe(false);
  });

  it("skips files that do not contain any detected components", async () => {
    await writeFixture("src/util.tsx", `export const helper = () => 1;\n`);
    const report = await generateStoriesForProject({
      projectRoot,
      framework: "react",
      targets: ["src/*.tsx"],
    });
    expect(report.results).toEqual([]);
  });

  it("falls through namespace objects and picks the next function-valued component", async () => {
    await writeFixture(
      "src/Pack.tsx",
      `
        const PackBody = (props: { label: string }) => null;
        export const Pack = { Body: PackBody };
        export const PackBodyAlias = PackBody;
      `,
    );
    const report = await generateStoriesForProject({
      projectRoot,
      framework: "react",
      targets: ["src/*.tsx"],
    });
    expect(report.results).toHaveLength(1);
    expect(report.results[0]?.componentName).toBe("PackBodyAlias");
    expect(report.results[0]?.status).toBe("written");
  });

  it("reports skipped-no-component when no detected component resolves to a function", async () => {
    await writeFixture(
      "src/Pack.tsx",
      `
        const helperFunction = () => 1;
        export const Pack = { value: helperFunction };
      `,
    );
    const report = await generateStoriesForProject({
      projectRoot,
      framework: "react",
      targets: ["src/*.tsx"],
    });
    expect(report.results[0]?.status).toBe("skipped-no-component");
    expect(await fileExists(join(projectRoot, "src/Pack.stories.tsx"))).toBe(false);
  });

  it("uses the framework's default component glob when targets is empty", async () => {
    await writeFixture(
      "src/Button.tsx",
      `export const Button = (props: { label: string }) => null;\n`,
    );
    const report = await generateStoriesForProject({
      projectRoot,
      framework: "react",
      targets: [],
    });
    expect(report.results).toHaveLength(1);
    expect(report.results[0]?.componentName).toBe("Button");
  });
});
